version: '3.1'
services: 
  API:
    image: 'abn-amro-test.jar'
    container_name: abn-amro-test
    ports: 
      - 9095:9095
    depends_on: 
      PostgreSQL: 
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/transactions
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
           
  PostgreSQL: 
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  Zookeeper: 
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - 2181  
  
  Kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: Kafka
      KAFKA_ZOOKEEPER_CONNECT: Zookeeper:2181
      KAFKA_CREATE_TOPIC: "test-topic:1:3"
    depends_on:
      - Zookeeper  

      